CREATE TABLE CUSTOMERS(
    CUSTOMER_ID INTEGER NOT NULL,
    FIRST_NAME VARCHAR (100) NOT NULL,
    LAST_NAME VARCHAR (100),
    PHONE VARCHAR (20),
    EMAIL VARCHAR (255), 
    STREET VARCHAR (100),
    CITY VARCHAR (100),
    STATE VARCHAR (100),
    ZIPCODE INTEGER,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE STORES(
    STORE_ID INTEGER NOT NULL,
    STORE_NAME VARCHAR,
    PHONE VARCHAR (100),
    EMAIL VARCHAR (255), 
    STREET VARCHAR (100),
    CITY VARCHAR (100),
    STATE VARCHAR (100),
    ZIPCODE INTEGER,
    PRIMARY KEY (STORE_ID)
);

CREATE TABLE CATEGORIES(
    CATEGORY_ID INTEGER NOT NULL,
    CATEGORY_NAME VARCHAR (100),
    PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE BRANDS(
    BRAND_ID INTEGER NOT NULL,
    BRAND_NAME VARCHAR (100),
    PRIMARY KEY (BRAND_ID)
);

CREATE TABLE PRODUCTS(
    PRODUCT_ID INTEGER NOT NULL, 
    PRODUCT_NAME VARCHAR (100),
    BRAND_ID INTEGER NOT NULL,
    CATEGORY_ID INTEGER NOT NULL,
    MODEL_YEAR INTEGER,
    LIST_PRICE FLOAT,
    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(BRAND_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);

CREATE TABLE STOCKS(
    STORE_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    QUANTITY INTEGER,
    PRIMARY KEY (STORE_ID, PRODUCT_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE STAFF(
    STAFF_ID INTEGER NOT NULL,
    FIRST_NAME VARCHAR (100) NOT NULL,
    LAST_NAME VARCHAR (100),
    EMAIL VARCHAR (255),
    PHONE VARCHAR (100),
    ACTIVE INTEGER,
    STORE_ID INTEGER NOT NULL, 
    MANAGER_ID INTEGER,
    PRIMARY KEY (STAFF_ID),
    FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID),
    FOREIGN KEY (MANAGER_ID) REFERENCES STAFF(STAFF_ID)
);

CREATE TABLE ORDERS(
    ORDER_ID INTEGER NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    ORDER_STATUS INTEGER,
    ORDER_DATE VARCHAR (100),
    REQUIRED_DATE VARCHAR (100),
    SHIPPED_DATE VARCHAR (100),
    STORE_ID INTEGER NOT NULL,
    STAFF_ID INTEGER NOT NULL,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID),
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
);


CREATE TABLE ORDER_ITEMS(
    ITEM_ID INTEGER NOT NULL,
    ORDER_ID INTEGER NOT NULL, 
    PRODUCT_ID INTEGER NOT NULL, 
    QUANTITY INTEGER,
    LIST_PRICE FLOAT,
    DISCOUNT FLOAT,
    PRIMARY KEY (ITEM_ID, ORDER_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);